import 'package:country_pickers/country.dart';

final List<CountryPicked> countryList = [
  CountryPicked(
    isoCode: "AD",
    phoneCode: "376",
    name: "Andorra",
    iso3Code: "AND",
    placeholder: "312 345",
  ),
  CountryPicked(
    isoCode: "AE",
    phoneCode: "971",
    name: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    iso3Code: "ARE",
    placeholder: "050 123 4567",
  ),
  CountryPicked(
    isoCode: "AF",
    phoneCode: "93",
    name: "Afghanistan (‫افغانستان‬‎)",
    iso3Code: "AFG",
    placeholder: "070 123 4567",
  ),
  CountryPicked(
    isoCode: "AG",
    phoneCode: "1268",
    name: "Antigua and Barbuda",
    iso3Code: "ATG",
    placeholder: "(268) 464-1234",
  ),
  CountryPicked(
    isoCode: "AI",
    phoneCode: "1264",
    name: "Anguilla",
    iso3Code: "AIA",
    placeholder: "(264) 235-1234",
  ),
  CountryPicked(
    isoCode: "AL",
    phoneCode: "355",
    name: "Albania (Shqipëri)",
    iso3Code: "ALB",
    placeholder: "066 123 4567",
  ),
  CountryPicked(
    isoCode: "AM",
    phoneCode: "374",
    name: "Armenia (Հայաստան)",
    iso3Code: "ARM",
    placeholder: "077 123456",
  ),
  CountryPicked(
    isoCode: "AN",
    phoneCode: "599",
    name: "Netherlands Antilles",
    iso3Code: "AN",
    placeholder: "318 1234",
  ),
  CountryPicked(
    isoCode: "AO",
    phoneCode: "244",
    name: "Angola",
    iso3Code: "AGO",
    placeholder: "923 123 456",
  ),
  CountryPicked(
    isoCode: "AQ",
    phoneCode: "672",
    name: "Antarctica",
    iso3Code: "ATA",
    placeholder: "3 81234",
  ),
  CountryPicked(
    isoCode: "AR",
    phoneCode: "54",
    name: "Argentina",
    iso3Code: "ARG",
    placeholder: "011 15-2345-6789",
  ),
  CountryPicked(
    isoCode: "AS",
    phoneCode: "1684",
    name: "American Samoa",
    iso3Code: "ASM",
    placeholder: "(684) 733-1234",
  ),
  CountryPicked(
    isoCode: "AT",
    phoneCode: "43",
    name: "Austria (Österreich)",
    iso3Code: "AUT",
    placeholder: "0664 123456",
  ),
  CountryPicked(
    isoCode: "AU",
    phoneCode: "61",
    name: "Australia",
    iso3Code: "AUS",
    placeholder: "0412 345 678",
  ),
  CountryPicked(
    isoCode: "AW",
    phoneCode: "297",
    name: "Aruba",
    iso3Code: "ABW",
    placeholder: "560 1234",
  ),
  CountryPicked(
    isoCode: "AX",
    phoneCode: "358",
    name: "Åland Islands",
    iso3Code: "ALA",
    placeholder: "041 2345678",
  ),
  CountryPicked(
    isoCode: "AZ",
    phoneCode: "994",
    name: "Azerbaijan (Azərbaycan)",
    iso3Code: "AZE",
    placeholder: "040 123 45 67",
  ),
  CountryPicked(
    isoCode: "BA",
    phoneCode: "387",
    name: "Bosnia and Herzegovina (Босна и Херцеговина)",
    iso3Code: "BIH",
    placeholder: "061 123 456",
  ),
  CountryPicked(
    isoCode: "BB",
    phoneCode: "1246",
    name: "Barbados",
    iso3Code: "BRB",
    placeholder: "(246) 250-1234",
  ),
  CountryPicked(
    isoCode: "BD",
    phoneCode: "880",
    name: "Bangladesh (বাংলাদেশ)",
    iso3Code: "BGD",
    placeholder: "01812-345678",
  ),
  CountryPicked(
    isoCode: "BE",
    phoneCode: "32",
    name: "Belgium (België)",
    iso3Code: "BEL",
    placeholder: "0470 12 34 56",
  ),
  CountryPicked(
    isoCode: "BF",
    phoneCode: "226",
    name: "Burkina Faso",
    iso3Code: "BFA",
    placeholder: "70 12 34 56",
  ),
  CountryPicked(
    isoCode: "BG",
    phoneCode: "359",
    name: "Bulgaria (България)",
    iso3Code: "BGR",
    placeholder: "048 123 456",
  ),
  CountryPicked(
    isoCode: "BH",
    phoneCode: "973",
    name: "Bahrain (‫البحرين‬‎)",
    iso3Code: "BHR",
    placeholder: "3600 1234",
  ),
  CountryPicked(
    isoCode: "BI",
    phoneCode: "257",
    name: "Burundi (Uburundi)",
    iso3Code: "BDI",
    placeholder: "79 56 12 34",
  ),
  CountryPicked(
    isoCode: "BJ",
    phoneCode: "229",
    name: "Benin (Bénin)",
    iso3Code: "BEN",
    placeholder: "90 01 12 34",
  ),
  CountryPicked(
    isoCode: "BL",
    phoneCode: "590",
    name: "Saint Barthélemy",
    iso3Code: "BLM",
    placeholder: "0690 30-1234",
  ),
  CountryPicked(
    isoCode: "BM",
    phoneCode: "1441",
    name: "Bermuda",
    iso3Code: "BMU",
    placeholder: "(441) 370-1234",
  ),
  CountryPicked(
    isoCode: "BN",
    phoneCode: "673",
    name: "Brunei Darussalam",
    iso3Code: "BRN",
    placeholder: "712 3456",
  ),
  CountryPicked(
    isoCode: "BO",
    phoneCode: "591",
    name: "Bolivia",
    iso3Code: "BOL",
    placeholder: "71234567",
  ),
  CountryPicked(
    isoCode: "BQ",
    phoneCode: "599",
    name: "Caribbean Netherlands",
    iso3Code: "BES",
    placeholder: "318 1234",
  ),
  CountryPicked(
    isoCode: "BR",
    phoneCode: "55",
    name: "Brazil (Brasil)",
    iso3Code: "BRA",
    placeholder: "(11) 96123-4567",
  ),
  CountryPicked(
    isoCode: "BS",
    phoneCode: "1242",
    name: "Bahamas",
    iso3Code: "BHS",
    placeholder: "(242) 359-1234",
  ),
  CountryPicked(
    isoCode: "BT",
    phoneCode: "975",
    name: "Bhutan (འབྲུག)",
    iso3Code: "BTN",
    placeholder: "17 12 34 56",
  ),
  CountryPicked(
    isoCode: "BV",
    phoneCode: "47",
    name: "Bouvet Island",
    iso3Code: "BVT",
    placeholder: "",
  ),
  CountryPicked(
    isoCode: "BW",
    phoneCode: "267",
    name: "Botswana",
    iso3Code: "BWA",
    placeholder: "71 123 456",
  ),
  CountryPicked(
    isoCode: "BY",
    phoneCode: "375",
    name: "Belarus (Беларусь)",
    iso3Code: "BLR",
    placeholder: "8 029 491-19-11",
  ),
  CountryPicked(
    isoCode: "BZ",
    phoneCode: "501",
    name: "Belize",
    iso3Code: "BLZ",
    placeholder: "622-1234",
  ),
  CountryPicked(
    isoCode: "CA",
    phoneCode: "1",
    name: "Canada",
    iso3Code: "CAN",
    placeholder: "(204) 234-5678",
  ),
  CountryPicked(
    isoCode: "CC",
    phoneCode: "61",
    name: "Cocos (Keeling) Islands",
    iso3Code: "CCK",
    placeholder: "0412 345 678",
  ),
  CountryPicked(
    isoCode: "CD",
    phoneCode: "243",
    name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
    iso3Code: "COD",
    placeholder: "0991 234 567",
  ),
  CountryPicked(
    isoCode: "CF",
    phoneCode: "236",
    name: "Central African Republic (République centrafricaine)",
    iso3Code: "CAF",
    placeholder: "70 01 23 45",
  ),
  CountryPicked(
    isoCode: "CG",
    phoneCode: "242",
    name: "Congo (Republic) (Congo-Brazzaville)",
    iso3Code: "COG",
    placeholder: "06 123 4567",
  ),
  CountryPicked(
    isoCode: "CH",
    phoneCode: "41",
    name: "Switzerland (Schweiz)",
    iso3Code: "CHE",
    placeholder: "078 123 45 67",
  ),
  CountryPicked(
    isoCode: "CI",
    phoneCode: "225",
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
    placeholder: "01 23 45 67",
  ),
  CountryPicked(
    isoCode: "CK",
    phoneCode: "682",
    name: "Cook Islands",
    iso3Code: "COK",
    placeholder: "71 234",
  ),
  CountryPicked(
    isoCode: "CL",
    phoneCode: "56",
    name: "Chile",
    iso3Code: "CHL",
    placeholder: "09 6123 4567",
  ),
  CountryPicked(
    isoCode: "CM",
    phoneCode: "237",
    name: "Cameroon (Cameroun)",
    iso3Code: "CMR",
    placeholder: "6 71 23 45 67",
  ),
  CountryPicked(
    isoCode: "CN",
    phoneCode: "86",
    name: "China (中国)",
    iso3Code: "CHN",
    placeholder: "131 2345 6789",
  ),
  CountryPicked(
    isoCode: "CO",
    phoneCode: "57",
    name: "Colombia",
    iso3Code: "COL",
    placeholder: "321 1234567",
  ),
  CountryPicked(
    isoCode: "CR",
    phoneCode: "506",
    name: "Costa Rica",
    iso3Code: "CRI",
    placeholder: "8312 3456",
  ),
  CountryPicked(
    isoCode: "CU",
    phoneCode: "53",
    name: "Cuba",
    iso3Code: "CUB",
    placeholder: "05 1234567",
  ),
  CountryPicked(
    isoCode: "CV",
    phoneCode: "238",
    name: "Cape Verde (Kabu Verdi)",
    iso3Code: "CPV",
    placeholder: "991 12 34",
  ),
  CountryPicked(
    isoCode: "CW",
    phoneCode: "599",
    name: "Curaçao",
    iso3Code: "CUW",
    placeholder: "9 518 1234",
  ),
  CountryPicked(
    isoCode: "CX",
    phoneCode: "61",
    name: "Christmas Island",
    iso3Code: "CXR",
    placeholder: "0412 345 678",
  ),
  CountryPicked(
    isoCode: "CY",
    phoneCode: "357",
    name: "Cyprus (Κύπρος)",
    iso3Code: "CYP",
    placeholder: "96 123456",
  ),
  CountryPicked(
    isoCode: "CZ",
    phoneCode: "420",
    name: "Czech Republic (Česká republika)",
    iso3Code: "CZE",
    placeholder: "601 123 456",
  ),
  CountryPicked(
    isoCode: "DE",
    phoneCode: "49",
    name: "Germany (Deutschland)",
    iso3Code: "DEU",
    placeholder: "01512 3456789",
  ),
  CountryPicked(
    isoCode: "DJ",
    phoneCode: "253",
    name: "Djibouti",
    iso3Code: "DJI",
    placeholder: "77 83 10 01",
  ),
  CountryPicked(
    isoCode: "DK",
    phoneCode: "45",
    name: "Denmark (Danmark)",
    iso3Code: "DNK",
    placeholder: "20 12 34 56",
  ),
  CountryPicked(
    isoCode: "DM",
    phoneCode: "1767",
    name: "Dominica",
    iso3Code: "DMA",
    placeholder: "(767) 225-1234",
  ),
  CountryPicked(
    isoCode: "DO",
    phoneCode: "1849",
    name: "Dominican Republic (República Dominicana)",
    iso3Code: "DOM",
    placeholder: "(809) 234-5678",
  ),
  CountryPicked(
    isoCode: "DZ",
    phoneCode: "213",
    name: "Algeria (‫الجزائر‬‎)",
    iso3Code: "DZA",
    placeholder: "0551 23 45 67",
  ),
  CountryPicked(
    isoCode: "EC",
    phoneCode: "593",
    name: "Ecuador",
    iso3Code: "ECU",
    placeholder: "099 123 4567",
  ),
  CountryPicked(
    isoCode: "EE",
    phoneCode: "372",
    name: "Estonia (Eesti)",
    iso3Code: "EST",
    placeholder: "5123 4567",
  ),
  CountryPicked(
    isoCode: "EG",
    phoneCode: "20",
    name: "Egypt (‫مصر‬‎)",
    iso3Code: "EGY",
    placeholder: "0100 123 4567",
  ),
  CountryPicked(
    isoCode: "EH",
    phoneCode: "212",
    name: "Western Sahara (‫الصحراء الغربية‬‎)",
    iso3Code: "ESH",
    placeholder: "0650-123456",
  ),
  CountryPicked(
    isoCode: "ER",
    phoneCode: "291",
    name: "Eritrea",
    iso3Code: "ERI",
    placeholder: "07 123 456",
  ),
  CountryPicked(
    isoCode: "ES",
    phoneCode: "34",
    name: "Spain (España)",
    iso3Code: "ESP",
    placeholder: "612 34 56 78",
  ),
  CountryPicked(
    isoCode: "ET",
    phoneCode: "251",
    name: "Ethiopia",
    iso3Code: "ETH",
    placeholder: "091 123 4567",
  ),
  CountryPicked(
    isoCode: "FI",
    phoneCode: "358",
    name: "Finland (Suomi)",
    iso3Code: "FIN",
    placeholder: "041 2345678",
  ),
  CountryPicked(
    isoCode: "FJ",
    phoneCode: "679",
    name: "Fiji",
    iso3Code: "FJI",
    placeholder: "701 2345",
  ),
  CountryPicked(
    isoCode: "FK",
    phoneCode: "500",
    name: "Falkland Islands (Islas Malvinas)",
    iso3Code: "FLK",
    placeholder: "51234",
  ),
  CountryPicked(
    isoCode: "FM",
    phoneCode: "691",
    name: "Micronesia",
    iso3Code: "FSM",
    placeholder: "350 1234",
  ),
  CountryPicked(
    isoCode: "FO",
    phoneCode: "298",
    name: "Faroe Islands (Føroyar)",
    iso3Code: "FRO",
    placeholder: "211234",
  ),
  CountryPicked(
    isoCode: "FR",
    phoneCode: "33",
    name: "France",
    iso3Code: "FRA",
    placeholder: "06 12 34 56 78",
  ),
  CountryPicked(
    isoCode: "GA",
    phoneCode: "241",
    name: "Gabon",
    iso3Code: "GAB",
    placeholder: "06 03 12 34",
  ),
  CountryPicked(
    isoCode: "GB",
    phoneCode: "44",
    name: "United Kingdom",
    iso3Code: "GBR",
    placeholder: "07400 123456",
  ),
  CountryPicked(
    isoCode: "GB-ENG",
    phoneCode: "44",
    name: "England",
    iso3Code: "GBR",
    placeholder: "07400 123456",
  ),
  CountryPicked(
    isoCode: "GB-NIR",
    phoneCode: "44",
    name: "Northern Ireland",
    iso3Code: "GBR",
    placeholder: "07400 123456",
  ),
  CountryPicked(
    isoCode: "GB-SCT",
    phoneCode: "44",
    name: "Scotland",
    iso3Code: "GBR",
    placeholder: "07400 123456",
  ),
  CountryPicked(
    isoCode: "GB-WLS",
    phoneCode: "44",
    name: "Wales",
    iso3Code: "GBR",
    placeholder: "07400 123456",
  ),
  CountryPicked(
    isoCode: "GD",
    phoneCode: "1473",
    name: "Grenada",
    iso3Code: "GRD",
    placeholder: "(473) 403-1234",
  ),
  CountryPicked(
    isoCode: "GE",
    phoneCode: "995",
    name: "Georgia",
    iso3Code: "GEO",
    placeholder: "555 12 34 56",
  ),
  CountryPicked(
    isoCode: "GF",
    phoneCode: "594",
    name: "French Guiana (Guyane française)",
    iso3Code: "GUF",
    placeholder: "0694 20 12 34",
  ),
  CountryPicked(
    isoCode: "GG",
    phoneCode: "44-1481",
    name: "Guernsey",
    iso3Code: "GGY",
    placeholder: "07781 123456",
  ),
  CountryPicked(
    isoCode: "GH",
    phoneCode: "233",
    name: "Ghana (Gaana)",
    iso3Code: "GHA",
    placeholder: "023 123 4567",
  ),
  CountryPicked(
    isoCode: "GI",
    phoneCode: "350",
    name: "Gibraltar",
    iso3Code: "GIB",
    placeholder: "57123456",
  ),
  CountryPicked(
    isoCode: "GL",
    phoneCode: "299",
    name: "Greenland (Kalaallit Nunaat)",
    iso3Code: "GRL",
    placeholder: "22 12 34",
  ),
  CountryPicked(
    isoCode: "GM",
    phoneCode: "220",
    name: "Gambia",
    iso3Code: "GMB",
    placeholder: "301 2345",
  ),
  CountryPicked(
    isoCode: "GN",
    phoneCode: "224",
    name: "Guinea (Guinée)",
    iso3Code: "GIN",
    placeholder: "601 12 34 56",
  ),
  CountryPicked(
    isoCode: "GP",
    phoneCode: "590",
    name: "Guadeloupe",
    iso3Code: "GLP",
    placeholder: "0690 30-1234",
  ),
  CountryPicked(
    isoCode: "GQ",
    phoneCode: "240",
    name: "Equatorial Guinea (Guinea Ecuatorial)",
    iso3Code: "GNQ",
    placeholder: "222 123 456",
  ),
  CountryPicked(
    isoCode: "GR",
    phoneCode: "30",
    name: "Greece (Ελλάδα)",
    iso3Code: "GRC",
    placeholder: "691 234 5678",
  ),
  CountryPicked(
    isoCode: "GS",
    phoneCode: "500",
    name: "South Georgia and the South Sandwich Islands",
    iso3Code: "SGS",
    placeholder: "",
  ),
  CountryPicked(
    isoCode: "GT",
    phoneCode: "502",
    name: "Guatemala",
    iso3Code: "GTM",
    placeholder: "5123 4567",
  ),
  CountryPicked(
    isoCode: "GU",
    phoneCode: "1671",
    name: "Guam",
    iso3Code: "GUM",
    placeholder: "(671) 300-1234",
  ),
  CountryPicked(
    isoCode: "GW",
    phoneCode: "245",
    name: "Guinea-Bissau (Guiné Bissau)",
    iso3Code: "GNB",
    placeholder: "955 012 345",
  ),
  CountryPicked(
    isoCode: "GY",
    phoneCode: "592",
    name: "Guyana",
    iso3Code: "GUY",
    placeholder: "609 1234",
  ),
  CountryPicked(
    isoCode: "HK",
    phoneCode: "852",
    name: "Hong Kong (香港)",
    iso3Code: "HKG",
    placeholder: "5123 4567",
  ),
  CountryPicked(
    isoCode: "HM",
    phoneCode: "672",
    name: "Heard Island and McDonald Islands",
    iso3Code: "HMD",
    placeholder: "3 81234",
  ),
  CountryPicked(
    isoCode: "HN",
    phoneCode: "504",
    name: "Honduras",
    iso3Code: "HND",
    placeholder: "9123-4567",
  ),
  CountryPicked(
    isoCode: "HR",
    phoneCode: "385",
    name: "Croatia (Hrvatska)",
    iso3Code: "HRV",
    placeholder: "091 234 5678",
  ),
  CountryPicked(
    isoCode: "HT",
    phoneCode: "509",
    name: "Haiti",
    iso3Code: "HTI",
    placeholder: "34 10 1234",
  ),
  CountryPicked(
    isoCode: "HU",
    phoneCode: "36",
    name: "Hungary (Magyarország)",
    iso3Code: "HUN",
    placeholder: "(20) 123 4567",
  ),
  CountryPicked(
    isoCode: "ID",
    phoneCode: "62",
    name: "Indonesia",
    iso3Code: "IDN",
    placeholder: "0812-345-678",
  ),
  CountryPicked(
    isoCode: "IE",
    phoneCode: "353",
    name: "Ireland",
    iso3Code: "IRL",
    placeholder: "085 012 3456",
  ),
  CountryPicked(
    isoCode: "IL",
    phoneCode: "972",
    name: "Israel (‫ישראל‬‎)",
    iso3Code: "ISR",
    placeholder: "050-123-4567",
  ),
  CountryPicked(
    isoCode: "IM",
    phoneCode: "44",
    name: "Isle of Man",
    iso3Code: "IMN",
    placeholder: "07400 123456",
  ),
  CountryPicked(
    isoCode: "IN",
    phoneCode: "91",
    name: "India (भारत)",
    iso3Code: "IND",
    placeholder: "099876 54321",
  ),
  CountryPicked(
    isoCode: "IO",
    phoneCode: "246",
    name: "British Indian Ocean Territory",
    iso3Code: "IOT",
    placeholder: "380 1234",
  ),
  CountryPicked(
    isoCode: "IQ",
    phoneCode: "964",
    name: "Iraq (‫العراق‬‎)",
    iso3Code: "IRQ",
    placeholder: "0791 234 5678",
  ),
  CountryPicked(
    isoCode: "IR",
    phoneCode: "98",
    name: "Iran (‫ایران‬‎)",
    iso3Code: "IRN",
    placeholder: "0912 345 6789",
  ),
  CountryPicked(
    isoCode: "IS",
    phoneCode: "354",
    name: "Iceland (Ísland)",
    iso3Code: "ISL",
    placeholder: "611 1234",
  ),
  CountryPicked(
    isoCode: "IT",
    phoneCode: "39",
    name: "Italy (Italia)",
    iso3Code: "ITA",
    placeholder: "312 345 6789",
  ),
  CountryPicked(
    isoCode: "JE",
    phoneCode: "44-1534",
    name: "Jersey",
    iso3Code: "JEY",
    placeholder: "07797 123456",
  ),
  CountryPicked(
    isoCode: "JM",
    phoneCode: "1876",
    name: "Jamaica",
    iso3Code: "JAM",
    placeholder: "(876) 210-1234",
  ),
  CountryPicked(
    isoCode: "JO",
    phoneCode: "962",
    name: "Jordan (‫الأردن‬‎)",
    iso3Code: "JOR",
    placeholder: "07 9012 3456",
  ),
  CountryPicked(
    isoCode: "JP",
    phoneCode: "81",
    name: "Japan (日本)",
    iso3Code: "JPN",
    placeholder: "090-1234-5678",
  ),
  CountryPicked(
    isoCode: "KE",
    phoneCode: "254",
    name: "Kenya",
    iso3Code: "KEN",
    placeholder: "0712 123456",
  ),
  CountryPicked(
    isoCode: "KG",
    phoneCode: "996",
    name: "Kyrgyzstan (Кыргызстан)",
    iso3Code: "KGZ",
    placeholder: "0700 123 456",
  ),
  CountryPicked(
    isoCode: "KH",
    phoneCode: "855",
    name: "Cambodia (កម្ពុជា)",
    iso3Code: "KHM",
    placeholder: "091 234 567",
  ),
  CountryPicked(
    isoCode: "KI",
    phoneCode: "686",
    name: "Kiribati",
    iso3Code: "KIR",
    placeholder: "72012345",
  ),
  CountryPicked(
    isoCode: "KM",
    phoneCode: "269",
    name: "Comoros (‫جزر القمر‬‎)",
    iso3Code: "COM",
    placeholder: "321 23 45",
  ),
  CountryPicked(
    isoCode: "KN",
    phoneCode: "1869",
    name: "Saint Kitts and Nevis",
    iso3Code: "KNA",
    placeholder: "(869) 765-2917",
  ),
  CountryPicked(
    isoCode: "KP",
    phoneCode: "850",
    name: "North Korea (조선 민주주의 인민 공화국)",
    iso3Code: "PRK",
    placeholder: "0912 123 4567",
  ),
  CountryPicked(
    isoCode: "KR",
    phoneCode: "82",
    name: "South Korea (대한민국)",
    iso3Code: "KOR",
    placeholder: "010-0000-0000",
  ),
  CountryPicked(
    isoCode: "KW",
    phoneCode: "965",
    name: "Kuwait (‫الكويت‬‎)",
    iso3Code: "KWT",
    placeholder: "500 12345",
  ),
  CountryPicked(
    isoCode: "KY",
    phoneCode: "1345",
    name: "Cayman Islands",
    iso3Code: "CYM",
    placeholder: "(345) 323-1234",
  ),
  CountryPicked(
    isoCode: "KZ",
    phoneCode: "7",
    name: "Kazakhstan (Казахстан)",
    iso3Code: "KAZ",
    placeholder: "8 (771) 000 9998",
  ),
  CountryPicked(
    isoCode: "LA",
    phoneCode: "856",
    name: "Laos (ລາວ)",
    iso3Code: "LAO",
    placeholder: "020 23 123 456",
  ),
  CountryPicked(
    isoCode: "LB",
    phoneCode: "961",
    name: "Lebanon (‫لبنان‬‎)",
    iso3Code: "LBN",
    placeholder: "71 123 456",
  ),
  CountryPicked(
    isoCode: "LC",
    phoneCode: "1758",
    name: "Saint Lucia",
    iso3Code: "LCA",
    placeholder: "(758) 284-5678",
  ),
  CountryPicked(
    isoCode: "LI",
    phoneCode: "423",
    name: "Liechtenstein",
    iso3Code: "LIE",
    placeholder: "660 234 567",
  ),
  CountryPicked(
    isoCode: "LK",
    phoneCode: "94",
    name: "Sri Lanka (ශ්‍රී ලංකාව)",
    iso3Code: "LKA",
    placeholder: "071 234 5678",
  ),
  CountryPicked(
    isoCode: "LR",
    phoneCode: "231",
    name: "Liberia",
    iso3Code: "LBR",
    placeholder: "077 012 3456",
  ),
  CountryPicked(
    isoCode: "LS",
    phoneCode: "266",
    name: "Lesotho",
    iso3Code: "LSO",
    placeholder: "5012 3456",
  ),
  CountryPicked(
    isoCode: "LT",
    phoneCode: "370",
    name: "Lithuania (Lietuva)",
    iso3Code: "LTU",
    placeholder: "(8-612) 34567",
  ),
  CountryPicked(
    isoCode: "LU",
    phoneCode: "352",
    name: "Luxembourg",
    iso3Code: "LUX",
    placeholder: "628 123 456",
  ),
  CountryPicked(
    isoCode: "LV",
    phoneCode: "371",
    name: "Latvia (Latvija)",
    iso3Code: "LVA",
    placeholder: "21 234 567",
  ),
  CountryPicked(
    isoCode: "LY",
    phoneCode: "218",
    name: "Libya (‫ليبيا‬‎)",
    iso3Code: "LBY",
    placeholder: "091-2345678",
  ),
  CountryPicked(
    isoCode: "MA",
    phoneCode: "212",
    name: "Morocco (‫المغرب‬‎)",
    iso3Code: "MAR",
    placeholder: "0650-123456",
  ),
  CountryPicked(
    isoCode: "MC",
    phoneCode: "377",
    name: "Monaco",
    iso3Code: "MCO",
    placeholder: "06 12 34 56 78",
  ),
  CountryPicked(
    isoCode: "MD",
    phoneCode: "373",
    name: "Moldova (Republica Moldova)",
    iso3Code: "MDA",
    placeholder: "0621 12 345",
  ),
  CountryPicked(
    isoCode: "ME",
    phoneCode: "382",
    name: "Montenegro (Crna Gora)",
    iso3Code: "MNE",
    placeholder: "067 622 901",
  ),
  CountryPicked(
    isoCode: "MF",
    phoneCode: "590",
    name: "Saint Martin (Saint-Martin (partie française))",
    iso3Code: "MAF",
    placeholder: "0690 30-1234",
  ),
  CountryPicked(
    isoCode: "MG",
    phoneCode: "261",
    name: "Madagascar (Madagasikara)",
    iso3Code: "MDG",
    placeholder: "032 12 345 67",
  ),
  CountryPicked(
    isoCode: "MH",
    phoneCode: "692",
    name: "Marshall Islands",
    iso3Code: "MHL",
    placeholder: "235-1234",
  ),
  CountryPicked(
    isoCode: "MK",
    phoneCode: "389",
    name: "Macedonia (FYROM) (Македонија)",
    iso3Code: "MKD",
    placeholder: "072 345 678",
  ),
  CountryPicked(
    isoCode: "ML",
    phoneCode: "223",
    name: "Mali",
    iso3Code: "MLI",
    placeholder: "65 01 23 45",
  ),
  CountryPicked(
    isoCode: "MM",
    phoneCode: "95",
    name: "Myanmar (Burma) (မြန်မာ)",
    iso3Code: "MMR",
    placeholder: "09 212 3456",
  ),
  CountryPicked(
    isoCode: "MN",
    phoneCode: "976",
    name: "Mongolia (Монгол)",
    iso3Code: "MNG",
    placeholder: "8812 3456",
  ),
  CountryPicked(
    isoCode: "MO",
    phoneCode: "853",
    name: "Macau (澳門)",
    iso3Code: "MAC",
    placeholder: "6612 3456",
  ),
  CountryPicked(
    isoCode: "MP",
    phoneCode: "1670",
    name: "Northern Mariana Islands",
    iso3Code: "MNP",
    placeholder: "(670) 234-5678",
  ),
  CountryPicked(
    isoCode: "MQ",
    phoneCode: "596",
    name: "Martinique",
    iso3Code: "MTQ",
    placeholder: "0696 20 12 34",
  ),
  CountryPicked(
    isoCode: "MR",
    phoneCode: "222",
    name: "Mauritania (‫موريتانيا‬‎)",
    iso3Code: "MRT",
    placeholder: "22 12 34 56",
  ),
  CountryPicked(
    isoCode: "MS",
    phoneCode: "1664",
    name: "Montserrat",
    iso3Code: "MSR",
    placeholder: "(664) 491-3456",
  ),
  CountryPicked(
    isoCode: "MT",
    phoneCode: "356",
    name: "Malta",
    iso3Code: "MLT",
    placeholder: "9696 1234",
  ),
  CountryPicked(
    isoCode: "MU",
    phoneCode: "230",
    name: "Mauritius (Moris)",
    iso3Code: "MUS",
    placeholder: "5251 2345",
  ),
  CountryPicked(
    isoCode: "MV",
    phoneCode: "960",
    name: "Maldives",
    iso3Code: "MDV",
    placeholder: "771-2345",
  ),
  CountryPicked(
    isoCode: "MW",
    phoneCode: "265",
    name: "Malawi",
    iso3Code: "MWI",
    placeholder: "0991 23 45 67",
  ),
  CountryPicked(
    isoCode: "MX",
    phoneCode: "52",
    name: "Mexico (México)",
    iso3Code: "MEX",
    placeholder: "044 222 123 4567",
  ),
  CountryPicked(
    isoCode: "MY",
    phoneCode: "60",
    name: "Malaysia",
    iso3Code: "MYS",
    placeholder: "012-345 6789",
  ),
  CountryPicked(
    isoCode: "MZ",
    phoneCode: "258",
    name: "Mozambique (Moçambique)",
    iso3Code: "MOZ",
    placeholder: "82 123 4567",
  ),
  CountryPicked(
    isoCode: "NA",
    phoneCode: "264",
    name: "Namibia (Namibië)",
    iso3Code: "NAM",
    placeholder: "081 123 4567",
  ),
  CountryPicked(
    isoCode: "NC",
    phoneCode: "687",
    name: "New Caledonia (Nouvelle-Calédonie)",
    iso3Code: "NCL",
    placeholder: "75.12.34",
  ),
  CountryPicked(
    isoCode: "NE",
    phoneCode: "227",
    name: "Niger (Nijar)",
    iso3Code: "NER",
    placeholder: "93 12 34 56",
  ),
  CountryPicked(
    isoCode: "NF",
    phoneCode: "672",
    name: "Norfolk Island",
    iso3Code: "NFK",
    placeholder: "3 81234",
  ),
  CountryPicked(
    isoCode: "NG",
    phoneCode: "234",
    name: "Nigeria",
    iso3Code: "NGA",
    placeholder: "0802 123 4567",
  ),
  CountryPicked(
    isoCode: "NI",
    phoneCode: "505",
    name: "Nicaragua",
    iso3Code: "NIC",
    placeholder: "8123 4567",
  ),
  CountryPicked(
    isoCode: "NL",
    phoneCode: "31",
    name: "Netherlands",
    iso3Code: "NLD",
    placeholder: "06 12345678",
  ),
  CountryPicked(
    isoCode: "NO",
    phoneCode: "47",
    name: "Norway (Norge)",
    iso3Code: "NOR",
    placeholder: "406 12 345",
  ),
  CountryPicked(
    isoCode: "NP",
    phoneCode: "977",
    name: "Nepal (नेपाल)",
    iso3Code: "NPL",
    placeholder: "984-1234567",
  ),
  CountryPicked(
    isoCode: "NR",
    phoneCode: "674",
    name: "Nauru",
    iso3Code: "NRU",
    placeholder: "555 1234",
  ),
  CountryPicked(
    isoCode: "NU",
    phoneCode: "683",
    name: "Niue",
    iso3Code: "NIU",
    placeholder: "1234",
  ),
  CountryPicked(
    isoCode: "NZ",
    phoneCode: "64",
    name: "New Zealand",
    iso3Code: "NZL",
    placeholder: "021 123 4567",
  ),
  CountryPicked(
    isoCode: "OM",
    phoneCode: "968",
    name: "Oman (‫عُمان‬‎)",
    iso3Code: "OMN",
    placeholder: "9212 3456",
  ),
  CountryPicked(
    isoCode: "PA",
    phoneCode: "507",
    name: "Panama (Panamá)",
    iso3Code: "PAN",
    placeholder: "6001-2345",
  ),
  CountryPicked(
    isoCode: "PE",
    phoneCode: "51",
    name: "Peru (Perú)",
    iso3Code: "PER",
    placeholder: "912 345 678",
  ),
  CountryPicked(
    isoCode: "PF",
    phoneCode: "689",
    name: "French Polynesia (Polynésie française)",
    iso3Code: "PYF",
    placeholder: "87 12 34 56",
  ),
  CountryPicked(
    isoCode: "PG",
    phoneCode: "675",
    name: "Papua New Guinea",
    iso3Code: "PNG",
    placeholder: "681 2345",
  ),
  CountryPicked(
    isoCode: "PH",
    phoneCode: "63",
    name: "Philippines",
    iso3Code: "PHL",
    placeholder: "0905 123 4567",
  ),
  CountryPicked(
    isoCode: "PK",
    phoneCode: "92",
    name: "Pakistan (‫پاکستان‬‎)",
    iso3Code: "PAK",
    placeholder: "0301 2345678",
  ),
  CountryPicked(
    isoCode: "PL",
    phoneCode: "48",
    name: "Poland (Polska)",
    iso3Code: "POL",
    placeholder: "512 345 678",
  ),
  CountryPicked(
    isoCode: "PM",
    phoneCode: "508",
    name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    iso3Code: "SPM",
    placeholder: "055 12-34",
  ),
  CountryPicked(
    isoCode: "PN",
    phoneCode: "64",
    name: "Pitcairn",
    iso3Code: "PCN",
    placeholder: "",
  ),
  CountryPicked(
    isoCode: "PR",
    phoneCode: "1",
    name: "Puerto Rico",
    iso3Code: "PRI",
    placeholder: "(787) 234-5678",
  ),
  CountryPicked(
    isoCode: "PS",
    phoneCode: "970",
    name: "Palestine (‫فلسطين‬‎)",
    iso3Code: "PSE",
    placeholder: "0599 123 456",
  ),
  CountryPicked(
    isoCode: "PT",
    phoneCode: "351",
    name: "Portugal",
    iso3Code: "PRT",
    placeholder: "912 345 678",
  ),
  CountryPicked(
    isoCode: "PW",
    phoneCode: "680",
    name: "Palau",
    iso3Code: "PLW",
    placeholder: "620 1234",
  ),
  CountryPicked(
    isoCode: "PY",
    phoneCode: "595",
    name: "Paraguay",
    iso3Code: "PRY",
    placeholder: "0961 456789",
  ),
  CountryPicked(
    isoCode: "QA",
    phoneCode: "974",
    name: "Qatar (‫قطر‬‎)",
    iso3Code: "QAT",
    placeholder: "3312 3456",
  ),
  CountryPicked(
    isoCode: "RE",
    phoneCode: "262",
    name: "Réunion (La Réunion)",
    iso3Code: "REU",
    placeholder: "0692 12 34 56",
  ),
  CountryPicked(
    isoCode: "RO",
    phoneCode: "40",
    name: "Romania (România)",
    iso3Code: "ROU",
    placeholder: "0712 345 678",
  ),
  CountryPicked(
    isoCode: "RS",
    phoneCode: "381",
    name: "Serbia (Србија)",
    iso3Code: "SRB",
    placeholder: "060 1234567",
  ),
  CountryPicked(
    isoCode: "RU",
    phoneCode: "7",
    name: "Russia (Россия)",
    iso3Code: "RUS",
    placeholder: "8 (912) 345-67-89",
  ),
  CountryPicked(
    isoCode: "RW",
    phoneCode: "250",
    name: "Rwanda",
    iso3Code: "RWA",
    placeholder: "0720 123 456",
  ),
  CountryPicked(
    isoCode: "SA",
    phoneCode: "966",
    name: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    iso3Code: "SAU",
    placeholder: "051 234 5678",
  ),
  CountryPicked(
    isoCode: "SB",
    phoneCode: "677",
    name: "Solomon Islands",
    iso3Code: "SLB",
    placeholder: "74 21234",
  ),
  CountryPicked(
    isoCode: "SC",
    phoneCode: "248",
    name: "Seychelles",
    iso3Code: "SYC",
    placeholder: "2 510 123",
  ),
  CountryPicked(
    isoCode: "SD",
    phoneCode: "249",
    name: "Sudan (‫السودان‬‎)",
    iso3Code: "SDN",
    placeholder: "091 123 1234",
  ),
  CountryPicked(
    isoCode: "SE",
    phoneCode: "46",
    name: "Sweden (Sverige)",
    iso3Code: "SWE",
    placeholder: "070-123 45 67",
  ),
  CountryPicked(
    isoCode: "SG",
    phoneCode: "65",
    name: "Singapore",
    iso3Code: "SGP",
    placeholder: "8123 4567",
  ),
  CountryPicked(
    isoCode: "SH",
    phoneCode: "290",
    name: "Saint Helena",
    iso3Code: "SHN",
    placeholder: "0690 30-1234",
  ),
  CountryPicked(
    isoCode: "SI",
    phoneCode: "386",
    name: "Slovenia (Slovenija)",
    iso3Code: "SVN",
    placeholder: "031 234 567",
  ),
  CountryPicked(
    isoCode: "SJ",
    phoneCode: "47",
    name: "Svalbard and Jan Mayen",
    iso3Code: "SJM",
    placeholder: "412 34 567",
  ),
  CountryPicked(
    isoCode: "SK",
    phoneCode: "421",
    name: "Slovakia (Slovensko)",
    iso3Code: "SVK",
    placeholder: "0912 123 456",
  ),
  CountryPicked(
    isoCode: "SL",
    phoneCode: "232",
    name: "Sierra Leone",
    iso3Code: "SLE",
    placeholder: "(025) 123456",
  ),
  CountryPicked(
    isoCode: "SM",
    phoneCode: "378",
    name: "San Marino",
    iso3Code: "SMR",
    placeholder: "66 66 12 12",
  ),
  CountryPicked(
    isoCode: "SN",
    phoneCode: "221",
    name: "Senegal (Sénégal)",
    iso3Code: "SEN",
    placeholder: "70 123 45 67",
  ),
  CountryPicked(
    isoCode: "SO",
    phoneCode: "252",
    name: "Somalia (Soomaaliya)",
    iso3Code: "SOM",
    placeholder: "7 1123456",
  ),
  CountryPicked(
    isoCode: "SR",
    phoneCode: "597",
    name: "Suriname",
    iso3Code: "SUR",
    placeholder: "741-2345",
  ),
  CountryPicked(
    isoCode: "SS",
    phoneCode: "211",
    name: "South Sudan (‫جنوب السودان‬‎)",
    iso3Code: "SSD",
    placeholder: "0977 123 456",
  ),
  CountryPicked(
    isoCode: "ST",
    phoneCode: "239",
    name: "São Tomé and Príncipe (São Tomé e Príncipe)",
    iso3Code: "STP",
    placeholder: "981 2345",
  ),
  CountryPicked(
    isoCode: "SV",
    phoneCode: "503",
    name: "El Salvador",
    iso3Code: "SLV",
    placeholder: "7012 3456",
  ),
  CountryPicked(
    isoCode: "SX",
    phoneCode: "1721",
    name: "Sint Maarten",
    iso3Code: "SXM",
    placeholder: "(721) 520-5678",
  ),
  CountryPicked(
    isoCode: "SY",
    phoneCode: "963",
    name: "Syria (‫سوريا‬‎)",
    iso3Code: "SYR",
    placeholder: "0944 567 890",
  ),
  CountryPicked(
    isoCode: "SZ",
    phoneCode: "268",
    name: "Swaziland",
    iso3Code: "SWZ",
    placeholder: "7612 3456",
  ),
  CountryPicked(
    isoCode: "TC",
    phoneCode: "1649",
    name: "Turks and Caicos Islands",
    iso3Code: "TCA",
    placeholder: "(649) 231-1234",
  ),
  CountryPicked(
    isoCode: "TD",
    phoneCode: "235",
    name: "Chad (Tchad)",
    iso3Code: "TCD",
    placeholder: "63 01 23 45",
  ),
  CountryPicked(
    isoCode: "TF",
    phoneCode: "262",
    name: "French Southern Territories",
    iso3Code: "ATF",
    placeholder: "",
  ),
  CountryPicked(
    isoCode: "TG",
    phoneCode: "228",
    name: "Togo",
    iso3Code: "TGO",
    placeholder: "90 11 23 45",
  ),
  CountryPicked(
    isoCode: "TH",
    phoneCode: "66",
    name: "Thailand (ไทย)",
    iso3Code: "THA",
    placeholder: "081 234 5678",
  ),
  CountryPicked(
    isoCode: "TJ",
    phoneCode: "992",
    name: "Tajikistan",
    iso3Code: "TJK",
    placeholder: "(8) 917 12 3456",
  ),
  CountryPicked(
    isoCode: "TK",
    phoneCode: "690",
    name: "Tokelau",
    iso3Code: "TKL",
    placeholder: "7290",
  ),
  CountryPicked(
    isoCode: "TL",
    phoneCode: "670",
    name: "Timor-Leste",
    iso3Code: "TLS",
    placeholder: "7721 2345",
  ),
  CountryPicked(
    isoCode: "TM",
    phoneCode: "993",
    name: "Turkmenistan",
    iso3Code: "TKM",
    placeholder: "8 66 123456",
  ),
  CountryPicked(
    isoCode: "TN",
    phoneCode: "216",
    name: "Tunisia (‫تونس‬‎)",
    iso3Code: "TUN",
    placeholder: "20 123 456",
  ),
  CountryPicked(
    isoCode: "TO",
    phoneCode: "676",
    name: "Tonga",
    iso3Code: "TON",
    placeholder: "771 5123",
  ),
  CountryPicked(
    isoCode: "TR",
    phoneCode: "90",
    name: "Turkey (Türkiye)",
    iso3Code: "TUR",
    placeholder: "0501 234 5678",
  ),
  CountryPicked(
    isoCode: "TT",
    phoneCode: "1868",
    name: "Trinidad and Tobago",
    iso3Code: "TTO",
    placeholder: "(868) 291-1234",
  ),
  CountryPicked(
    isoCode: "TV",
    phoneCode: "688",
    name: "Tuvalu",
    iso3Code: "TUV",
    placeholder: "901234",
  ),
  CountryPicked(
    isoCode: "TW",
    phoneCode: "886",
    name: "Taiwan (台灣)",
    iso3Code: "TWN",
    placeholder: "0912 345 678",
  ),
  CountryPicked(
    isoCode: "TZ",
    phoneCode: "255",
    name: "Tanzania",
    iso3Code: "TZA",
    placeholder: "0621 234 567",
  ),
  CountryPicked(
    isoCode: "UA",
    phoneCode: "380",
    name: "Ukraine (Україна)",
    iso3Code: "UKR",
    placeholder: "039 123 4567",
  ),
  CountryPicked(
    isoCode: "UG",
    phoneCode: "256",
    name: "Uganda",
    iso3Code: "UGA",
    placeholder: "0712 345678",
  ),
  CountryPicked(
    isoCode: "UM",
    phoneCode: "1",
    name: "US Minor Outlying Islands",
    iso3Code: "UMI",
    placeholder: "",
  ),
  CountryPicked(
    isoCode: "US",
    phoneCode: "1",
    name: "United States",
    iso3Code: "USA",
    placeholder: "(201) 555-0123",
  ),
  CountryPicked(
    isoCode: "UY",
    phoneCode: "598",
    name: "Uruguay",
    iso3Code: "URY",
    placeholder: "094 231 234",
  ),
  CountryPicked(
    isoCode: "UZ",
    phoneCode: "998",
    name: "Uzbekistan (Oʻzbekiston)",
    iso3Code: "UZB",
    placeholder: "8 91 234 56 78",
  ),
  CountryPicked(
    isoCode: "VA",
    phoneCode: "379",
    name: "Vatican City (Città del Vaticano)",
    iso3Code: "VAT",
    placeholder: "321 345 6789",
  ),
  CountryPicked(
    isoCode: "VC",
    phoneCode: "1784",
    name: "Saint Vincent and the Grenadines",
    iso3Code: "VCT",
    placeholder: "(784) 430-1234",
  ),
  CountryPicked(
    isoCode: "VE",
    phoneCode: "58",
    name: "Venezuela",
    iso3Code: "VEN",
    placeholder: "0412-1234567",
  ),
  CountryPicked(
    isoCode: "VG",
    phoneCode: "1284",
    name: "Virgin Islands, British",
    iso3Code: "VGB",
    placeholder: "(284) 300-1234",
  ),
  CountryPicked(
    isoCode: "VI",
    phoneCode: "1340",
    name: "U.S. Virgin Islands",
    iso3Code: "VIR",
    placeholder: "(340) 642-1234",
  ),
  CountryPicked(
    isoCode: "VN",
    phoneCode: "84",
    name: "Vietnam (Việt Nam)",
    iso3Code: "VNM",
    placeholder: "091 234 56 78",
  ),
  CountryPicked(
    isoCode: "VU",
    phoneCode: "678",
    name: "Vanuatu",
    iso3Code: "VUT",
    placeholder: "591 2345",
  ),
  CountryPicked(
    isoCode: "WF",
    phoneCode: "681",
    name: "Wallis and Futuna",
    iso3Code: "WLF",
    placeholder: "50 12 34",
  ),
  CountryPicked(
    isoCode: "XK",
    phoneCode: "383",
    name: "Kosovo",
    iso3Code: "KOS",
    placeholder: "",
  ),
  CountryPicked(
    isoCode: "WS",
    phoneCode: "685",
    name: "Samoa",
    iso3Code: "WSM",
    placeholder: "601234",
  ),
  CountryPicked(
    isoCode: "YE",
    phoneCode: "967",
    name: "Yemen (‫اليمن‬‎)",
    iso3Code: "YEM",
    placeholder: "0712 345 678",
  ),
  CountryPicked(
    isoCode: "YT",
    phoneCode: "262",
    name: "Mayotte",
    iso3Code: "MYT",
    placeholder: "0639 12 34 56",
  ),
  CountryPicked(
    isoCode: "ZA",
    phoneCode: "27",
    name: "South Africa",
    iso3Code: "ZAF",
    placeholder: "071 123 4567",
  ),
  CountryPicked(
    isoCode: "ZM",
    phoneCode: "260",
    name: "Zambia",
    iso3Code: "ZMB",
    placeholder: "095 5123456",
  ),
  CountryPicked(
    isoCode: "ZW",
    phoneCode: "263",
    name: "Zimbabwe",
    iso3Code: "ZWE",
    placeholder: "071 123 4567",
  ),
];
